// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/gaston2.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DoseMatrixToNumericMatrix
Rcpp::NumericMatrix DoseMatrixToNumericMatrix(Rcpp::XPtr<SNPmatrix<SNPdosage>> pM);
RcppExport SEXP _gaston2_DoseMatrixToNumericMatrix(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(DoseMatrixToNumericMatrix(pM));
    return rcpp_result_gen;
END_RCPP
}
// LD_pair_moments
double LD_pair_moments(Rcpp::XPtr<SNPmatrix<>> pM, size_t i1, size_t i2, bool r_scale);
RcppExport SEXP _gaston2_LD_pair_moments(SEXP pMSEXP, SEXP i1SEXP, SEXP i2SEXP, SEXP r_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< size_t >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< size_t >::type i2(i2SEXP);
    Rcpp::traits::input_parameter< bool >::type r_scale(r_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_pair_moments(pM, i1, i2, r_scale));
    return rcpp_result_gen;
END_RCPP
}
// LD_square_moments
Rcpp::NumericMatrix LD_square_moments(Rcpp::XPtr<SNPmatrix<>> pM, size_t i1, size_t i2, bool r_scale);
RcppExport SEXP _gaston2_LD_square_moments(SEXP pMSEXP, SEXP i1SEXP, SEXP i2SEXP, SEXP r_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< size_t >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< size_t >::type i2(i2SEXP);
    Rcpp::traits::input_parameter< bool >::type r_scale(r_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_square_moments(pM, i1, i2, r_scale));
    return rcpp_result_gen;
END_RCPP
}
// LD_chunk_moments
Rcpp::NumericMatrix LD_chunk_moments(Rcpp::XPtr<SNPmatrix<>> pM, size_t i1, size_t i2, size_t j1, size_t j2, bool r_scale);
RcppExport SEXP _gaston2_LD_chunk_moments(SEXP pMSEXP, SEXP i1SEXP, SEXP i2SEXP, SEXP j1SEXP, SEXP j2SEXP, SEXP r_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< size_t >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< size_t >::type i2(i2SEXP);
    Rcpp::traits::input_parameter< size_t >::type j1(j1SEXP);
    Rcpp::traits::input_parameter< size_t >::type j2(j2SEXP);
    Rcpp::traits::input_parameter< bool >::type r_scale(r_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_chunk_moments(pM, i1, i2, j1, j2, r_scale));
    return rcpp_result_gen;
END_RCPP
}
// LD_pair_EM
double LD_pair_EM(Rcpp::XPtr<SNPmatrix<>> pM, size_t i1, size_t i2, bool r_scale);
RcppExport SEXP _gaston2_LD_pair_EM(SEXP pMSEXP, SEXP i1SEXP, SEXP i2SEXP, SEXP r_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< size_t >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< size_t >::type i2(i2SEXP);
    Rcpp::traits::input_parameter< bool >::type r_scale(r_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_pair_EM(pM, i1, i2, r_scale));
    return rcpp_result_gen;
END_RCPP
}
// LD_square_EM
Rcpp::NumericMatrix LD_square_EM(Rcpp::XPtr<SNPmatrix<>> pM, size_t i1, size_t i2, bool r_scale);
RcppExport SEXP _gaston2_LD_square_EM(SEXP pMSEXP, SEXP i1SEXP, SEXP i2SEXP, SEXP r_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< size_t >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< size_t >::type i2(i2SEXP);
    Rcpp::traits::input_parameter< bool >::type r_scale(r_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_square_EM(pM, i1, i2, r_scale));
    return rcpp_result_gen;
END_RCPP
}
// LD_chunk_EM
Rcpp::NumericMatrix LD_chunk_EM(Rcpp::XPtr<SNPmatrix<>> pM, size_t i1, size_t i2, size_t j1, size_t j2, bool r_scale);
RcppExport SEXP _gaston2_LD_chunk_EM(SEXP pMSEXP, SEXP i1SEXP, SEXP i2SEXP, SEXP j1SEXP, SEXP j2SEXP, SEXP r_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< size_t >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< size_t >::type i2(i2SEXP);
    Rcpp::traits::input_parameter< size_t >::type j1(j1SEXP);
    Rcpp::traits::input_parameter< size_t >::type j2(j2SEXP);
    Rcpp::traits::input_parameter< bool >::type r_scale(r_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_chunk_EM(pM, i1, i2, j1, j2, r_scale));
    return rcpp_result_gen;
END_RCPP
}
// LD_square_moments_mmatrix
SEXP LD_square_moments_mmatrix(Rcpp::XPtr<SNPmatrix<>> pM, size_t i1, size_t i2, std::string path, bool r_scale, bool usefloat);
RcppExport SEXP _gaston2_LD_square_moments_mmatrix(SEXP pMSEXP, SEXP i1SEXP, SEXP i2SEXP, SEXP pathSEXP, SEXP r_scaleSEXP, SEXP usefloatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< size_t >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< size_t >::type i2(i2SEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type r_scale(r_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type usefloat(usefloatSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_square_moments_mmatrix(pM, i1, i2, path, r_scale, usefloat));
    return rcpp_result_gen;
END_RCPP
}
// LD_chunk_moments_mmatrix
SEXP LD_chunk_moments_mmatrix(Rcpp::XPtr<SNPmatrix<>> pM, size_t i1, size_t i2, size_t j1, size_t j2, std::string path, bool r_scale, bool usefloat);
RcppExport SEXP _gaston2_LD_chunk_moments_mmatrix(SEXP pMSEXP, SEXP i1SEXP, SEXP i2SEXP, SEXP j1SEXP, SEXP j2SEXP, SEXP pathSEXP, SEXP r_scaleSEXP, SEXP usefloatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< size_t >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< size_t >::type i2(i2SEXP);
    Rcpp::traits::input_parameter< size_t >::type j1(j1SEXP);
    Rcpp::traits::input_parameter< size_t >::type j2(j2SEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type r_scale(r_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type usefloat(usefloatSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_chunk_moments_mmatrix(pM, i1, i2, j1, j2, path, r_scale, usefloat));
    return rcpp_result_gen;
END_RCPP
}
// LD_square_EM_mmatrix
SEXP LD_square_EM_mmatrix(Rcpp::XPtr<SNPmatrix<>> pM, size_t i1, size_t i2, std::string path, bool r_scale, bool usefloat);
RcppExport SEXP _gaston2_LD_square_EM_mmatrix(SEXP pMSEXP, SEXP i1SEXP, SEXP i2SEXP, SEXP pathSEXP, SEXP r_scaleSEXP, SEXP usefloatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< size_t >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< size_t >::type i2(i2SEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type r_scale(r_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type usefloat(usefloatSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_square_EM_mmatrix(pM, i1, i2, path, r_scale, usefloat));
    return rcpp_result_gen;
END_RCPP
}
// LD_chunk_EM_mmatrix
SEXP LD_chunk_EM_mmatrix(Rcpp::XPtr<SNPmatrix<>> pM, size_t i1, size_t i2, size_t j1, size_t j2, std::string path, bool r_scale, bool usefloat);
RcppExport SEXP _gaston2_LD_chunk_EM_mmatrix(SEXP pMSEXP, SEXP i1SEXP, SEXP i2SEXP, SEXP j1SEXP, SEXP j2SEXP, SEXP pathSEXP, SEXP r_scaleSEXP, SEXP usefloatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< size_t >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< size_t >::type i2(i2SEXP);
    Rcpp::traits::input_parameter< size_t >::type j1(j1SEXP);
    Rcpp::traits::input_parameter< size_t >::type j2(j2SEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type r_scale(r_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type usefloat(usefloatSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_chunk_EM_mmatrix(pM, i1, i2, j1, j2, path, r_scale, usefloat));
    return rcpp_result_gen;
END_RCPP
}
// LD_thin_
void LD_thin_(Rcpp::XPtr<SNPmatrix<>> pM, double threshold, int max_dist_bp, double max_dist_cM, Rcpp::LogicalVector which_keep);
RcppExport SEXP _gaston2_LD_thin_(SEXP pMSEXP, SEXP thresholdSEXP, SEXP max_dist_bpSEXP, SEXP max_dist_cMSEXP, SEXP which_keepSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type max_dist_bp(max_dist_bpSEXP);
    Rcpp::traits::input_parameter< double >::type max_dist_cM(max_dist_cMSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type which_keep(which_keepSEXP);
    LD_thin_(pM, threshold, max_dist_bp, max_dist_cM, which_keep);
    return R_NilValue;
END_RCPP
}
// SNPMatrixToIntegerMatrix
Rcpp::IntegerMatrix SNPMatrixToIntegerMatrix(Rcpp::XPtr<SNPmatrix<>> pM);
RcppExport SEXP _gaston2_SNPMatrixToIntegerMatrix(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(SNPMatrixToIntegerMatrix(pM));
    return rcpp_result_gen;
END_RCPP
}
// SNPMatrixToNumericMatrix
Rcpp::NumericMatrix SNPMatrixToNumericMatrix(Rcpp::XPtr<SNPmatrix<>> pM);
RcppExport SEXP _gaston2_SNPMatrixToNumericMatrix(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(SNPMatrixToNumericMatrix(pM));
    return rcpp_result_gen;
END_RCPP
}
// bindIndstoDosagematrixDisk_
Rcpp::XPtr<SNPmatrix<SNPdosageDisk<mio::access_mode::write>>> bindIndstoDosagematrixDisk_(Rcpp::XPtr<SNPmatrix<SNPdosage>> first, Rcpp::XPtr<SNPmatrix<SNPdosage>> second, std::string path);
RcppExport SEXP _gaston2_bindIndstoDosagematrixDisk_(SEXP firstSEXP, SEXP secondSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type first(firstSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type second(secondSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(bindIndstoDosagematrixDisk_(first, second, path));
    return rcpp_result_gen;
END_RCPP
}
// bindIndstoDosagematrixMemory_
Rcpp::XPtr<SNPmatrix<SNPdosageMemory>> bindIndstoDosagematrixMemory_(Rcpp::XPtr<SNPmatrix<SNPdosage>> first, Rcpp::XPtr<SNPmatrix<SNPdosage>> second);
RcppExport SEXP _gaston2_bindIndstoDosagematrixMemory_(SEXP firstSEXP, SEXP secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type first(firstSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type second(secondSEXP);
    rcpp_result_gen = Rcpp::wrap(bindIndstoDosagematrixMemory_(first, second));
    return rcpp_result_gen;
END_RCPP
}
// bindIndstoSNPmatrixDisk_
Rcpp::XPtr<SNPmatrix<SNPvectorDisk<mio::access_mode::write>>> bindIndstoSNPmatrixDisk_(Rcpp::XPtr<SNPmatrix<SNPvector>> first, Rcpp::XPtr<SNPmatrix<SNPvector>> second, std::string newmatrix_path);
RcppExport SEXP _gaston2_bindIndstoSNPmatrixDisk_(SEXP firstSEXP, SEXP secondSEXP, SEXP newmatrix_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPvector>> >::type first(firstSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPvector>> >::type second(secondSEXP);
    Rcpp::traits::input_parameter< std::string >::type newmatrix_path(newmatrix_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(bindIndstoSNPmatrixDisk_(first, second, newmatrix_path));
    return rcpp_result_gen;
END_RCPP
}
// bindIndstoSNPmatrixMemory_
Rcpp::XPtr<SNPmatrix<SNPvectorMemory>> bindIndstoSNPmatrixMemory_(Rcpp::XPtr<SNPmatrix<SNPvector>> first, Rcpp::XPtr<SNPmatrix<SNPvector>> second);
RcppExport SEXP _gaston2_bindIndstoSNPmatrixMemory_(SEXP firstSEXP, SEXP secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPvector>> >::type first(firstSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPvector>> >::type second(secondSEXP);
    rcpp_result_gen = Rcpp::wrap(bindIndstoSNPmatrixMemory_(first, second));
    return rcpp_result_gen;
END_RCPP
}
// cbind_SNPmatrix
Rcpp::XPtr<SNPmatrix<>> cbind_SNPmatrix(Rcpp::XPtr<SNPmatrix<>> first_matrix, Rcpp::XPtr<SNPmatrix<>> scd_matrix);
RcppExport SEXP _gaston2_cbind_SNPmatrix(SEXP first_matrixSEXP, SEXP scd_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type first_matrix(first_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type scd_matrix(scd_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(cbind_SNPmatrix(first_matrix, scd_matrix));
    return rcpp_result_gen;
END_RCPP
}
// cbind_Dosagematrix
Rcpp::XPtr<SNPmatrix<SNPdosage>> cbind_Dosagematrix(Rcpp::XPtr<SNPmatrix<SNPdosage>> first_matrix, Rcpp::XPtr<SNPmatrix<SNPdosage>> scd_matrix);
RcppExport SEXP _gaston2_cbind_Dosagematrix(SEXP first_matrixSEXP, SEXP scd_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type first_matrix(first_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type scd_matrix(scd_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(cbind_Dosagematrix(first_matrix, scd_matrix));
    return rcpp_result_gen;
END_RCPP
}
// computeSNPStats
void computeSNPStats(Rcpp::XPtr<SNPmatrix<SNPvector>> pM);
RcppExport SEXP _gaston2_computeSNPStats(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPvector>> >::type pM(pMSEXP);
    computeSNPStats(pM);
    return R_NilValue;
END_RCPP
}
// computeSNPStatsDosage
void computeSNPStatsDosage(Rcpp::XPtr<SNPmatrix<SNPdosage>> pM);
RcppExport SEXP _gaston2_computeSNPStatsDosage(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type pM(pMSEXP);
    computeSNPStatsDosage(pM);
    return R_NilValue;
END_RCPP
}
// exportSNPStats
void exportSNPStats(Rcpp::XPtr<SNPmatrix<SNPvector>> pM);
RcppExport SEXP _gaston2_exportSNPStats(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPvector>> >::type pM(pMSEXP);
    exportSNPStats(pM);
    return R_NilValue;
END_RCPP
}
// exportSNPStatsDosage
void exportSNPStatsDosage(Rcpp::XPtr<SNPmatrix<SNPdosage>> pM);
RcppExport SEXP _gaston2_exportSNPStatsDosage(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type pM(pMSEXP);
    exportSNPStatsDosage(pM);
    return R_NilValue;
END_RCPP
}
// dimDosematrix
Rcpp::IntegerVector dimDosematrix(Rcpp::XPtr<SNPmatrix<>> pM);
RcppExport SEXP _gaston2_dimDosematrix(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(dimDosematrix(pM));
    return rcpp_result_gen;
END_RCPP
}
// dimSNPmatrix
Rcpp::IntegerVector dimSNPmatrix(Rcpp::XPtr<SNPmatrix<>> pM);
RcppExport SEXP _gaston2_dimSNPmatrix(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(dimSNPmatrix(pM));
    return rcpp_result_gen;
END_RCPP
}
// extractIndsfromDosagematrixDisk_
Rcpp::XPtr<SNPmatrix<SNPdosage>> extractIndsfromDosagematrixDisk_(Rcpp::XPtr<SNPmatrix<SNPdosage>> other, Rcpp::IntegerVector keep, std::string path_str);
RcppExport SEXP _gaston2_extractIndsfromDosagematrixDisk_(SEXP otherSEXP, SEXP keepSEXP, SEXP path_strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type other(otherSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< std::string >::type path_str(path_strSEXP);
    rcpp_result_gen = Rcpp::wrap(extractIndsfromDosagematrixDisk_(other, keep, path_str));
    return rcpp_result_gen;
END_RCPP
}
// extractIndsfromDosagematrixMemory_
Rcpp::XPtr<SNPmatrix<SNPdosage>> extractIndsfromDosagematrixMemory_(Rcpp::XPtr<SNPmatrix<SNPdosage>> other, Rcpp::IntegerVector keep);
RcppExport SEXP _gaston2_extractIndsfromDosagematrixMemory_(SEXP otherSEXP, SEXP keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type other(otherSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type keep(keepSEXP);
    rcpp_result_gen = Rcpp::wrap(extractIndsfromDosagematrixMemory_(other, keep));
    return rcpp_result_gen;
END_RCPP
}
// extractIndsfromSNPmatrixDisk_
Rcpp::XPtr<SNPmatrix<>> extractIndsfromSNPmatrixDisk_(Rcpp::XPtr<SNPmatrix<>> other, Rcpp::IntegerVector keep, std::string path_str);
RcppExport SEXP _gaston2_extractIndsfromSNPmatrixDisk_(SEXP otherSEXP, SEXP keepSEXP, SEXP path_strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type other(otherSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< std::string >::type path_str(path_strSEXP);
    rcpp_result_gen = Rcpp::wrap(extractIndsfromSNPmatrixDisk_(other, keep, path_str));
    return rcpp_result_gen;
END_RCPP
}
// extractIndsfromSNPmatrixMemory_
Rcpp::XPtr<SNPmatrix<>> extractIndsfromSNPmatrixMemory_(Rcpp::XPtr<SNPmatrix<>> other, Rcpp::IntegerVector keep);
RcppExport SEXP _gaston2_extractIndsfromSNPmatrixMemory_(SEXP otherSEXP, SEXP keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type other(otherSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type keep(keepSEXP);
    rcpp_result_gen = Rcpp::wrap(extractIndsfromSNPmatrixMemory_(other, keep));
    return rcpp_result_gen;
END_RCPP
}
// extractSNPsfromDosagematrix_
Rcpp::XPtr<SNPmatrix<SNPdosage>> extractSNPsfromDosagematrix_(Rcpp::XPtr<SNPmatrix<SNPdosage>> other, Rcpp::IntegerVector keep);
RcppExport SEXP _gaston2_extractSNPsfromDosagematrix_(SEXP otherSEXP, SEXP keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type other(otherSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type keep(keepSEXP);
    rcpp_result_gen = Rcpp::wrap(extractSNPsfromDosagematrix_(other, keep));
    return rcpp_result_gen;
END_RCPP
}
// extractSNPsfromSNPmatrix_
Rcpp::XPtr<SNPmatrix<>> extractSNPsfromSNPmatrix_(Rcpp::XPtr<SNPmatrix<>> other, Rcpp::IntegerVector keep);
RcppExport SEXP _gaston2_extractSNPsfromSNPmatrix_(SEXP otherSEXP, SEXP keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type other(otherSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type keep(keepSEXP);
    rcpp_result_gen = Rcpp::wrap(extractSNPsfromSNPmatrix_(other, keep));
    return rcpp_result_gen;
END_RCPP
}
// getGastonOptions_
Rcpp::List getGastonOptions_();
RcppExport SEXP _gaston2_getGastonOptions_() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getGastonOptions_());
    return rcpp_result_gen;
END_RCPP
}
// getIndStats
Rcpp::DataFrame getIndStats(Rcpp::XPtr<SNPmatrix<>> pM, bool compute);
RcppExport SEXP _gaston2_getIndStats(SEXP pMSEXP, SEXP computeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< bool >::type compute(computeSEXP);
    rcpp_result_gen = Rcpp::wrap(getIndStats(pM, compute));
    return rcpp_result_gen;
END_RCPP
}
// getIndStatsDosage
Rcpp::DataFrame getIndStatsDosage(Rcpp::XPtr<SNPmatrix<SNPdosage>> pM, bool compute);
RcppExport SEXP _gaston2_getIndStatsDosage(SEXP pMSEXP, SEXP computeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< bool >::type compute(computeSEXP);
    rcpp_result_gen = Rcpp::wrap(getIndStatsDosage(pM, compute));
    return rcpp_result_gen;
END_RCPP
}
// test_force_compute_indStats
void test_force_compute_indStats(Rcpp::XPtr<SNPmatrix<>> pM);
RcppExport SEXP _gaston2_test_force_compute_indStats(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    test_force_compute_indStats(pM);
    return R_NilValue;
END_RCPP
}
// getMode
std::string getMode(Rcpp::XPtr<SNPmatrix<>> pM);
RcppExport SEXP _gaston2_getMode(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(getMode(pM));
    return rcpp_result_gen;
END_RCPP
}
// getModeDosage
std::string getModeDosage(Rcpp::XPtr<SNPmatrix<SNPdosage>> pM);
RcppExport SEXP _gaston2_getModeDosage(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(getModeDosage(pM));
    return rcpp_result_gen;
END_RCPP
}
// getSNPStats
Rcpp::DataFrame getSNPStats(Rcpp::XPtr<SNPmatrix<>> pM);
RcppExport SEXP _gaston2_getSNPStats(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(getSNPStats(pM));
    return rcpp_result_gen;
END_RCPP
}
// getSNPStatsDosage
Rcpp::DataFrame getSNPStatsDosage(Rcpp::XPtr<SNPmatrix<SNPdosage>> pM);
RcppExport SEXP _gaston2_getSNPStatsDosage(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(getSNPStatsDosage(pM));
    return rcpp_result_gen;
END_RCPP
}
// grm_
Rcpp::NumericMatrix grm_(Rcpp::XPtr<SNPmatrix<>> pM);
RcppExport SEXP _gaston2_grm_(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(grm_(pM));
    return rcpp_result_gen;
END_RCPP
}
// grm_mmatrix
SEXP grm_mmatrix(Rcpp::XPtr<SNPmatrix<>> pM, std::string path);
RcppExport SEXP _gaston2_grm_mmatrix(SEXP pMSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(grm_mmatrix(pM, path));
    return rcpp_result_gen;
END_RCPP
}
// isAutosome_
Rcpp::LogicalVector isAutosome_(Rcpp::IntegerVector chr);
RcppExport SEXP _gaston2_isAutosome_(SEXP chrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type chr(chrSEXP);
    rcpp_result_gen = Rcpp::wrap(isAutosome_(chr));
    return rcpp_result_gen;
END_RCPP
}
// isX_
Rcpp::LogicalVector isX_(Rcpp::IntegerVector chr);
RcppExport SEXP _gaston2_isX_(SEXP chrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type chr(chrSEXP);
    rcpp_result_gen = Rcpp::wrap(isX_(chr));
    return rcpp_result_gen;
END_RCPP
}
// isY_
Rcpp::LogicalVector isY_(Rcpp::IntegerVector chr);
RcppExport SEXP _gaston2_isY_(SEXP chrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type chr(chrSEXP);
    rcpp_result_gen = Rcpp::wrap(isY_(chr));
    return rcpp_result_gen;
END_RCPP
}
// isMt_
Rcpp::LogicalVector isMt_(Rcpp::IntegerVector chr);
RcppExport SEXP _gaston2_isMt_(SEXP chrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type chr(chrSEXP);
    rcpp_result_gen = Rcpp::wrap(isMt_(chr));
    return rcpp_result_gen;
END_RCPP
}
// isnullptr
bool isnullptr(SEXP pointer);
RcppExport SEXP _gaston2_isnullptr(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(isnullptr(pointer));
    return rcpp_result_gen;
END_RCPP
}
// readBedFileDisk_
Rcpp::XPtr<SNPmatrix<>> readBedFileDisk_(std::string bedfile, std::string bimfile, std::string famfile);
RcppExport SEXP _gaston2_readBedFileDisk_(SEXP bedfileSEXP, SEXP bimfileSEXP, SEXP famfileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bedfile(bedfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type bimfile(bimfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type famfile(famfileSEXP);
    rcpp_result_gen = Rcpp::wrap(readBedFileDisk_(bedfile, bimfile, famfile));
    return rcpp_result_gen;
END_RCPP
}
// readBedFileMemory_
Rcpp::XPtr<SNPmatrix<>> readBedFileMemory_(std::string bedfile, std::string bimfile, std::string famfile);
RcppExport SEXP _gaston2_readBedFileMemory_(SEXP bedfileSEXP, SEXP bimfileSEXP, SEXP famfileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bedfile(bedfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type bimfile(bimfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type famfile(famfileSEXP);
    rcpp_result_gen = Rcpp::wrap(readBedFileMemory_(bedfile, bimfile, famfile));
    return rcpp_result_gen;
END_RCPP
}
// readBimFile
void readBimFile(Rcpp::XPtr<SNPmatrix<>> pM, std::string bimFile);
RcppExport SEXP _gaston2_readBimFile(SEXP pMSEXP, SEXP bimFileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< std::string >::type bimFile(bimFileSEXP);
    readBimFile(pM, bimFile);
    return R_NilValue;
END_RCPP
}
// readDosageFileMemory_
Rcpp::XPtr<SNPmatrix<SNPdosage>> readDosageFileMemory_(std::string bedfile, std::string bimfile, std::string famfile);
RcppExport SEXP _gaston2_readDosageFileMemory_(SEXP bedfileSEXP, SEXP bimfileSEXP, SEXP famfileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bedfile(bedfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type bimfile(bimfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type famfile(famfileSEXP);
    rcpp_result_gen = Rcpp::wrap(readDosageFileMemory_(bedfile, bimfile, famfile));
    return rcpp_result_gen;
END_RCPP
}
// readDosageFileDisk_
Rcpp::XPtr<SNPmatrix<SNPdosage>> readDosageFileDisk_(std::string bedfile, std::string bimfile, std::string famfile);
RcppExport SEXP _gaston2_readDosageFileDisk_(SEXP bedfileSEXP, SEXP bimfileSEXP, SEXP famfileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bedfile(bedfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type bimfile(bimfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type famfile(famfileSEXP);
    rcpp_result_gen = Rcpp::wrap(readDosageFileDisk_(bedfile, bimfile, famfile));
    return rcpp_result_gen;
END_RCPP
}
// readFamFile
void readFamFile(Rcpp::XPtr<SNPmatrix<>> pM, std::string famFile);
RcppExport SEXP _gaston2_readFamFile(SEXP pMSEXP, SEXP famFileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< std::string >::type famFile(famFileSEXP);
    readFamFile(pM, famFile);
    return R_NilValue;
END_RCPP
}
// setChrType
void setChrType(Rcpp::XPtr<SNPmatrix<SNPvector>> pM);
RcppExport SEXP _gaston2_setChrType(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPvector>> >::type pM(pMSEXP);
    setChrType(pM);
    return R_NilValue;
END_RCPP
}
// setGastonOptions
void setGastonOptions(Rcpp::List L);
RcppExport SEXP _gaston2_setGastonOptions(SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type L(LSEXP);
    setGastonOptions(L);
    return R_NilValue;
END_RCPP
}
// setMode
void setMode(Rcpp::XPtr<SNPmatrix<>> pM, std::string mode);
RcppExport SEXP _gaston2_setMode(SEXP pMSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    setMode(pM, mode);
    return R_NilValue;
END_RCPP
}
// setModeDosage
void setModeDosage(Rcpp::XPtr<SNPmatrix<SNPdosage>> pM, std::string mode);
RcppExport SEXP _gaston2_setModeDosage(SEXP pMSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    setModeDosage(pM, mode);
    return R_NilValue;
END_RCPP
}
// test_ds
Rcpp::DataFrame test_ds(Rcpp::DataFrame DF, Rcpp::IntegerVector In);
RcppExport SEXP _gaston2_test_ds(SEXP DFSEXP, SEXP InSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type DF(DFSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type In(InSEXP);
    rcpp_result_gen = Rcpp::wrap(test_ds(DF, In));
    return rcpp_result_gen;
END_RCPP
}
// test_ds2
Rcpp::DataFrame test_ds2();
RcppExport SEXP _gaston2_test_ds2() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_ds2());
    return rcpp_result_gen;
END_RCPP
}
// test_readBedFileMemory
IntegerVector test_readBedFileMemory(std::string filename, size_t n_ind, size_t n_snp, bool verbose);
RcppExport SEXP _gaston2_test_readBedFileMemory(SEXP filenameSEXP, SEXP n_indSEXP, SEXP n_snpSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_snp(n_snpSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(test_readBedFileMemory(filename, n_ind, n_snp, verbose));
    return rcpp_result_gen;
END_RCPP
}
// test_readBedFileDisk
IntegerVector test_readBedFileDisk(std::string filename, size_t n_ind, size_t n_snp);
RcppExport SEXP _gaston2_test_readBedFileDisk(SEXP filenameSEXP, SEXP n_indSEXP, SEXP n_snpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_snp(n_snpSEXP);
    rcpp_result_gen = Rcpp::wrap(test_readBedFileDisk(filename, n_ind, n_snp));
    return rcpp_result_gen;
END_RCPP
}
// test_delete
IntegerVector test_delete(std::string filename, size_t n_ind, size_t n_snp);
RcppExport SEXP _gaston2_test_delete(SEXP filenameSEXP, SEXP n_indSEXP, SEXP n_snpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_snp(n_snpSEXP);
    rcpp_result_gen = Rcpp::wrap(test_delete(filename, n_ind, n_snp));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_default
unsigned int test_performance_iterator_default(unsigned int n);
RcppExport SEXP _gaston2_test_performance_iterator_default(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_default(n));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_1
unsigned int test_performance_iterator_1(unsigned int n);
RcppExport SEXP _gaston2_test_performance_iterator_1(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_1(n));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_2
unsigned int test_performance_iterator_2(unsigned int n);
RcppExport SEXP _gaston2_test_performance_iterator_2(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_2(n));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_disk
unsigned int test_performance_iterator_disk(unsigned int n);
RcppExport SEXP _gaston2_test_performance_iterator_disk(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_disk(n));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_1d
unsigned int test_performance_iterator_1d(unsigned int n);
RcppExport SEXP _gaston2_test_performance_iterator_1d(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_1d(n));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_2d
unsigned int test_performance_iterator_2d(unsigned int n);
RcppExport SEXP _gaston2_test_performance_iterator_2d(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_2d(n));
    return rcpp_result_gen;
END_RCPP
}
// test_snp_stats
IntegerVector test_snp_stats(unsigned int n);
RcppExport SEXP _gaston2_test_snp_stats(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_snp_stats(n));
    return rcpp_result_gen;
END_RCPP
}
// test_snp_stats_all
IntegerMatrix test_snp_stats_all(int n_ind, int n_snp);
RcppExport SEXP _gaston2_test_snp_stats_all(SEXP n_indSEXP, SEXP n_snpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type n_snp(n_snpSEXP);
    rcpp_result_gen = Rcpp::wrap(test_snp_stats_all(n_ind, n_snp));
    return rcpp_result_gen;
END_RCPP
}
// test_snp_stats_d
IntegerVector test_snp_stats_d(unsigned int n);
RcppExport SEXP _gaston2_test_snp_stats_d(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_snp_stats_d(n));
    return rcpp_result_gen;
END_RCPP
}
// test_sums
IntegerVector test_sums(unsigned int n);
RcppExport SEXP _gaston2_test_sums(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_sums(n));
    return rcpp_result_gen;
END_RCPP
}
// test_mu_sigma
NumericMatrix test_mu_sigma(unsigned int n);
RcppExport SEXP _gaston2_test_mu_sigma(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_mu_sigma(n));
    return rcpp_result_gen;
END_RCPP
}
// test_modes_setsigma_one
NumericVector test_modes_setsigma_one(int mode);
RcppExport SEXP _gaston2_test_modes_setsigma_one(SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(test_modes_setsigma_one(mode));
    return rcpp_result_gen;
END_RCPP
}
// test_LD_square
NumericMatrix test_LD_square(int SNPnb1, int SNPnb2);
RcppExport SEXP _gaston2_test_LD_square(SEXP SNPnb1SEXP, SEXP SNPnb2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type SNPnb1(SNPnb1SEXP);
    Rcpp::traits::input_parameter< int >::type SNPnb2(SNPnb2SEXP);
    rcpp_result_gen = Rcpp::wrap(test_LD_square(SNPnb1, SNPnb2));
    return rcpp_result_gen;
END_RCPP
}
// test_contingency
SEXP test_contingency(int SNPnb1, int SNPnb2);
RcppExport SEXP _gaston2_test_contingency(SEXP SNPnb1SEXP, SEXP SNPnb2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type SNPnb1(SNPnb1SEXP);
    Rcpp::traits::input_parameter< int >::type SNPnb2(SNPnb2SEXP);
    rcpp_result_gen = Rcpp::wrap(test_contingency(SNPnb1, SNPnb2));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_stats_matrix
bool test_performance_stats_matrix();
RcppExport SEXP _gaston2_test_performance_stats_matrix() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_performance_stats_matrix());
    return rcpp_result_gen;
END_RCPP
}
// test_all_stats_matrix
IntegerMatrix test_all_stats_matrix();
RcppExport SEXP _gaston2_test_all_stats_matrix() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_all_stats_matrix());
    return rcpp_result_gen;
END_RCPP
}
// get_matrix_from_file
IntegerMatrix get_matrix_from_file(std::string path, size_t nbInds, size_t nbSNPs);
RcppExport SEXP _gaston2_get_matrix_from_file(SEXP pathSEXP, SEXP nbIndsSEXP, SEXP nbSNPsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< size_t >::type nbInds(nbIndsSEXP);
    Rcpp::traits::input_parameter< size_t >::type nbSNPs(nbSNPsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_matrix_from_file(path, nbInds, nbSNPs));
    return rcpp_result_gen;
END_RCPP
}
// test_copyConstructor
void test_copyConstructor();
RcppExport SEXP _gaston2_test_copyConstructor() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_copyConstructor();
    return R_NilValue;
END_RCPP
}
// test_first_scnd_ind
IntegerMatrix test_first_scnd_ind();
RcppExport SEXP _gaston2_test_first_scnd_ind() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_first_scnd_ind());
    return rcpp_result_gen;
END_RCPP
}
// set_num_thread
void set_num_thread(int num);
RcppExport SEXP _gaston2_set_num_thread(SEXP numSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num(numSEXP);
    set_num_thread(num);
    return R_NilValue;
END_RCPP
}
// testsuite
void testsuite(bool verbose);
RcppExport SEXP _gaston2_testsuite(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    testsuite(verbose);
    return R_NilValue;
END_RCPP
}
// ToDosagematrixDisk_
Rcpp::XPtr<SNPmatrix<SNPdosageDisk<mio::access_mode::write>>> ToDosagematrixDisk_(Rcpp::XPtr<SNPmatrix<SNPdosage>> pM, std::string newfile_name);
RcppExport SEXP _gaston2_ToDosagematrixDisk_(SEXP pMSEXP, SEXP newfile_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< std::string >::type newfile_name(newfile_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(ToDosagematrixDisk_(pM, newfile_name));
    return rcpp_result_gen;
END_RCPP
}
// ToDosagematrixMemory_
Rcpp::XPtr<SNPmatrix<SNPdosageMemory>> ToDosagematrixMemory_(Rcpp::XPtr<SNPmatrix<SNPdosage>> pM);
RcppExport SEXP _gaston2_ToDosagematrixMemory_(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPdosage>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(ToDosagematrixMemory_(pM));
    return rcpp_result_gen;
END_RCPP
}
// ToSNPmatrixDisk_
Rcpp::XPtr<SNPmatrix<SNPvectorDisk<mio::access_mode::write>>> ToSNPmatrixDisk_(Rcpp::XPtr<SNPmatrix<SNPvector>> pM, std::string newfile_name);
RcppExport SEXP _gaston2_ToSNPmatrixDisk_(SEXP pMSEXP, SEXP newfile_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPvector>> >::type pM(pMSEXP);
    Rcpp::traits::input_parameter< std::string >::type newfile_name(newfile_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(ToSNPmatrixDisk_(pM, newfile_name));
    return rcpp_result_gen;
END_RCPP
}
// ToSNPmatrixMemory_
Rcpp::XPtr<SNPmatrix<SNPvectorMemory>> ToSNPmatrixMemory_(Rcpp::XPtr<SNPmatrix<SNPvector>> pM);
RcppExport SEXP _gaston2_ToSNPmatrixMemory_(SEXP pMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<SNPmatrix<SNPvector>> >::type pM(pMSEXP);
    rcpp_result_gen = Rcpp::wrap(ToSNPmatrixMemory_(pM));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gaston2_DoseMatrixToNumericMatrix", (DL_FUNC) &_gaston2_DoseMatrixToNumericMatrix, 1},
    {"_gaston2_LD_pair_moments", (DL_FUNC) &_gaston2_LD_pair_moments, 4},
    {"_gaston2_LD_square_moments", (DL_FUNC) &_gaston2_LD_square_moments, 4},
    {"_gaston2_LD_chunk_moments", (DL_FUNC) &_gaston2_LD_chunk_moments, 6},
    {"_gaston2_LD_pair_EM", (DL_FUNC) &_gaston2_LD_pair_EM, 4},
    {"_gaston2_LD_square_EM", (DL_FUNC) &_gaston2_LD_square_EM, 4},
    {"_gaston2_LD_chunk_EM", (DL_FUNC) &_gaston2_LD_chunk_EM, 6},
    {"_gaston2_LD_square_moments_mmatrix", (DL_FUNC) &_gaston2_LD_square_moments_mmatrix, 6},
    {"_gaston2_LD_chunk_moments_mmatrix", (DL_FUNC) &_gaston2_LD_chunk_moments_mmatrix, 8},
    {"_gaston2_LD_square_EM_mmatrix", (DL_FUNC) &_gaston2_LD_square_EM_mmatrix, 6},
    {"_gaston2_LD_chunk_EM_mmatrix", (DL_FUNC) &_gaston2_LD_chunk_EM_mmatrix, 8},
    {"_gaston2_LD_thin_", (DL_FUNC) &_gaston2_LD_thin_, 5},
    {"_gaston2_SNPMatrixToIntegerMatrix", (DL_FUNC) &_gaston2_SNPMatrixToIntegerMatrix, 1},
    {"_gaston2_SNPMatrixToNumericMatrix", (DL_FUNC) &_gaston2_SNPMatrixToNumericMatrix, 1},
    {"_gaston2_bindIndstoDosagematrixDisk_", (DL_FUNC) &_gaston2_bindIndstoDosagematrixDisk_, 3},
    {"_gaston2_bindIndstoDosagematrixMemory_", (DL_FUNC) &_gaston2_bindIndstoDosagematrixMemory_, 2},
    {"_gaston2_bindIndstoSNPmatrixDisk_", (DL_FUNC) &_gaston2_bindIndstoSNPmatrixDisk_, 3},
    {"_gaston2_bindIndstoSNPmatrixMemory_", (DL_FUNC) &_gaston2_bindIndstoSNPmatrixMemory_, 2},
    {"_gaston2_cbind_SNPmatrix", (DL_FUNC) &_gaston2_cbind_SNPmatrix, 2},
    {"_gaston2_cbind_Dosagematrix", (DL_FUNC) &_gaston2_cbind_Dosagematrix, 2},
    {"_gaston2_computeSNPStats", (DL_FUNC) &_gaston2_computeSNPStats, 1},
    {"_gaston2_computeSNPStatsDosage", (DL_FUNC) &_gaston2_computeSNPStatsDosage, 1},
    {"_gaston2_exportSNPStats", (DL_FUNC) &_gaston2_exportSNPStats, 1},
    {"_gaston2_exportSNPStatsDosage", (DL_FUNC) &_gaston2_exportSNPStatsDosage, 1},
    {"_gaston2_dimDosematrix", (DL_FUNC) &_gaston2_dimDosematrix, 1},
    {"_gaston2_dimSNPmatrix", (DL_FUNC) &_gaston2_dimSNPmatrix, 1},
    {"_gaston2_extractIndsfromDosagematrixDisk_", (DL_FUNC) &_gaston2_extractIndsfromDosagematrixDisk_, 3},
    {"_gaston2_extractIndsfromDosagematrixMemory_", (DL_FUNC) &_gaston2_extractIndsfromDosagematrixMemory_, 2},
    {"_gaston2_extractIndsfromSNPmatrixDisk_", (DL_FUNC) &_gaston2_extractIndsfromSNPmatrixDisk_, 3},
    {"_gaston2_extractIndsfromSNPmatrixMemory_", (DL_FUNC) &_gaston2_extractIndsfromSNPmatrixMemory_, 2},
    {"_gaston2_extractSNPsfromDosagematrix_", (DL_FUNC) &_gaston2_extractSNPsfromDosagematrix_, 2},
    {"_gaston2_extractSNPsfromSNPmatrix_", (DL_FUNC) &_gaston2_extractSNPsfromSNPmatrix_, 2},
    {"_gaston2_getGastonOptions_", (DL_FUNC) &_gaston2_getGastonOptions_, 0},
    {"_gaston2_getIndStats", (DL_FUNC) &_gaston2_getIndStats, 2},
    {"_gaston2_getIndStatsDosage", (DL_FUNC) &_gaston2_getIndStatsDosage, 2},
    {"_gaston2_test_force_compute_indStats", (DL_FUNC) &_gaston2_test_force_compute_indStats, 1},
    {"_gaston2_getMode", (DL_FUNC) &_gaston2_getMode, 1},
    {"_gaston2_getModeDosage", (DL_FUNC) &_gaston2_getModeDosage, 1},
    {"_gaston2_getSNPStats", (DL_FUNC) &_gaston2_getSNPStats, 1},
    {"_gaston2_getSNPStatsDosage", (DL_FUNC) &_gaston2_getSNPStatsDosage, 1},
    {"_gaston2_grm_", (DL_FUNC) &_gaston2_grm_, 1},
    {"_gaston2_grm_mmatrix", (DL_FUNC) &_gaston2_grm_mmatrix, 2},
    {"_gaston2_isAutosome_", (DL_FUNC) &_gaston2_isAutosome_, 1},
    {"_gaston2_isX_", (DL_FUNC) &_gaston2_isX_, 1},
    {"_gaston2_isY_", (DL_FUNC) &_gaston2_isY_, 1},
    {"_gaston2_isMt_", (DL_FUNC) &_gaston2_isMt_, 1},
    {"_gaston2_isnullptr", (DL_FUNC) &_gaston2_isnullptr, 1},
    {"_gaston2_readBedFileDisk_", (DL_FUNC) &_gaston2_readBedFileDisk_, 3},
    {"_gaston2_readBedFileMemory_", (DL_FUNC) &_gaston2_readBedFileMemory_, 3},
    {"_gaston2_readBimFile", (DL_FUNC) &_gaston2_readBimFile, 2},
    {"_gaston2_readDosageFileMemory_", (DL_FUNC) &_gaston2_readDosageFileMemory_, 3},
    {"_gaston2_readDosageFileDisk_", (DL_FUNC) &_gaston2_readDosageFileDisk_, 3},
    {"_gaston2_readFamFile", (DL_FUNC) &_gaston2_readFamFile, 2},
    {"_gaston2_setChrType", (DL_FUNC) &_gaston2_setChrType, 1},
    {"_gaston2_setGastonOptions", (DL_FUNC) &_gaston2_setGastonOptions, 1},
    {"_gaston2_setMode", (DL_FUNC) &_gaston2_setMode, 2},
    {"_gaston2_setModeDosage", (DL_FUNC) &_gaston2_setModeDosage, 2},
    {"_gaston2_test_ds", (DL_FUNC) &_gaston2_test_ds, 2},
    {"_gaston2_test_ds2", (DL_FUNC) &_gaston2_test_ds2, 0},
    {"_gaston2_test_readBedFileMemory", (DL_FUNC) &_gaston2_test_readBedFileMemory, 4},
    {"_gaston2_test_readBedFileDisk", (DL_FUNC) &_gaston2_test_readBedFileDisk, 3},
    {"_gaston2_test_delete", (DL_FUNC) &_gaston2_test_delete, 3},
    {"_gaston2_test_performance_iterator_default", (DL_FUNC) &_gaston2_test_performance_iterator_default, 1},
    {"_gaston2_test_performance_iterator_1", (DL_FUNC) &_gaston2_test_performance_iterator_1, 1},
    {"_gaston2_test_performance_iterator_2", (DL_FUNC) &_gaston2_test_performance_iterator_2, 1},
    {"_gaston2_test_performance_iterator_disk", (DL_FUNC) &_gaston2_test_performance_iterator_disk, 1},
    {"_gaston2_test_performance_iterator_1d", (DL_FUNC) &_gaston2_test_performance_iterator_1d, 1},
    {"_gaston2_test_performance_iterator_2d", (DL_FUNC) &_gaston2_test_performance_iterator_2d, 1},
    {"_gaston2_test_snp_stats", (DL_FUNC) &_gaston2_test_snp_stats, 1},
    {"_gaston2_test_snp_stats_all", (DL_FUNC) &_gaston2_test_snp_stats_all, 2},
    {"_gaston2_test_snp_stats_d", (DL_FUNC) &_gaston2_test_snp_stats_d, 1},
    {"_gaston2_test_sums", (DL_FUNC) &_gaston2_test_sums, 1},
    {"_gaston2_test_mu_sigma", (DL_FUNC) &_gaston2_test_mu_sigma, 1},
    {"_gaston2_test_modes_setsigma_one", (DL_FUNC) &_gaston2_test_modes_setsigma_one, 1},
    {"_gaston2_test_LD_square", (DL_FUNC) &_gaston2_test_LD_square, 2},
    {"_gaston2_test_contingency", (DL_FUNC) &_gaston2_test_contingency, 2},
    {"_gaston2_test_performance_stats_matrix", (DL_FUNC) &_gaston2_test_performance_stats_matrix, 0},
    {"_gaston2_test_all_stats_matrix", (DL_FUNC) &_gaston2_test_all_stats_matrix, 0},
    {"_gaston2_get_matrix_from_file", (DL_FUNC) &_gaston2_get_matrix_from_file, 3},
    {"_gaston2_test_copyConstructor", (DL_FUNC) &_gaston2_test_copyConstructor, 0},
    {"_gaston2_test_first_scnd_ind", (DL_FUNC) &_gaston2_test_first_scnd_ind, 0},
    {"_gaston2_set_num_thread", (DL_FUNC) &_gaston2_set_num_thread, 1},
    {"_gaston2_testsuite", (DL_FUNC) &_gaston2_testsuite, 1},
    {"_gaston2_ToDosagematrixDisk_", (DL_FUNC) &_gaston2_ToDosagematrixDisk_, 2},
    {"_gaston2_ToDosagematrixMemory_", (DL_FUNC) &_gaston2_ToDosagematrixMemory_, 1},
    {"_gaston2_ToSNPmatrixDisk_", (DL_FUNC) &_gaston2_ToSNPmatrixDisk_, 2},
    {"_gaston2_ToSNPmatrixMemory_", (DL_FUNC) &_gaston2_ToSNPmatrixMemory_, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_gaston2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
