// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_readBedFileMemory
IntegerVector test_readBedFileMemory(std::string filename, size_t n_ind, size_t n_snp);
RcppExport SEXP _snipsnop_test_readBedFileMemory(SEXP filenameSEXP, SEXP n_indSEXP, SEXP n_snpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_snp(n_snpSEXP);
    rcpp_result_gen = Rcpp::wrap(test_readBedFileMemory(filename, n_ind, n_snp));
    return rcpp_result_gen;
END_RCPP
}
// test_readBedFileDisk
IntegerVector test_readBedFileDisk(std::string filename, size_t n_ind, size_t n_snp);
RcppExport SEXP _snipsnop_test_readBedFileDisk(SEXP filenameSEXP, SEXP n_indSEXP, SEXP n_snpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_snp(n_snpSEXP);
    rcpp_result_gen = Rcpp::wrap(test_readBedFileDisk(filename, n_ind, n_snp));
    return rcpp_result_gen;
END_RCPP
}
// test_delete
IntegerVector test_delete(std::string filename, size_t n_ind, size_t n_snp);
RcppExport SEXP _snipsnop_test_delete(SEXP filenameSEXP, SEXP n_indSEXP, SEXP n_snpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_snp(n_snpSEXP);
    rcpp_result_gen = Rcpp::wrap(test_delete(filename, n_ind, n_snp));
    return rcpp_result_gen;
END_RCPP
}
// test_readModes
IntegerVector test_readModes(std::string filename, size_t n_ind, size_t n_snp);
RcppExport SEXP _snipsnop_test_readModes(SEXP filenameSEXP, SEXP n_indSEXP, SEXP n_snpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_snp(n_snpSEXP);
    rcpp_result_gen = Rcpp::wrap(test_readModes(filename, n_ind, n_snp));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_default
unsigned int test_performance_iterator_default(unsigned int n);
RcppExport SEXP _snipsnop_test_performance_iterator_default(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_default(n));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_1
unsigned int test_performance_iterator_1(unsigned int n);
RcppExport SEXP _snipsnop_test_performance_iterator_1(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_1(n));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_2
unsigned int test_performance_iterator_2(unsigned int n);
RcppExport SEXP _snipsnop_test_performance_iterator_2(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_2(n));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_disk
unsigned int test_performance_iterator_disk(unsigned int n);
RcppExport SEXP _snipsnop_test_performance_iterator_disk(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_disk(n));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_1d
unsigned int test_performance_iterator_1d(unsigned int n);
RcppExport SEXP _snipsnop_test_performance_iterator_1d(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_1d(n));
    return rcpp_result_gen;
END_RCPP
}
// test_performance_iterator_2d
unsigned int test_performance_iterator_2d(unsigned int n);
RcppExport SEXP _snipsnop_test_performance_iterator_2d(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_performance_iterator_2d(n));
    return rcpp_result_gen;
END_RCPP
}
// test_snp_stats
IntegerVector test_snp_stats(unsigned int n);
RcppExport SEXP _snipsnop_test_snp_stats(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_snp_stats(n));
    return rcpp_result_gen;
END_RCPP
}
// test_snp_stats_d
IntegerVector test_snp_stats_d(unsigned int n);
RcppExport SEXP _snipsnop_test_snp_stats_d(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_snp_stats_d(n));
    return rcpp_result_gen;
END_RCPP
}
// test_sums
IntegerVector test_sums(unsigned int n);
RcppExport SEXP _snipsnop_test_sums(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_sums(n));
    return rcpp_result_gen;
END_RCPP
}
// test_mu_sigma
NumericVector test_mu_sigma(unsigned int n);
RcppExport SEXP _snipsnop_test_mu_sigma(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_mu_sigma(n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_snipsnop_test_readBedFileMemory", (DL_FUNC) &_snipsnop_test_readBedFileMemory, 3},
    {"_snipsnop_test_readBedFileDisk", (DL_FUNC) &_snipsnop_test_readBedFileDisk, 3},
    {"_snipsnop_test_delete", (DL_FUNC) &_snipsnop_test_delete, 3},
    {"_snipsnop_test_readModes", (DL_FUNC) &_snipsnop_test_readModes, 3},
    {"_snipsnop_test_performance_iterator_default", (DL_FUNC) &_snipsnop_test_performance_iterator_default, 1},
    {"_snipsnop_test_performance_iterator_1", (DL_FUNC) &_snipsnop_test_performance_iterator_1, 1},
    {"_snipsnop_test_performance_iterator_2", (DL_FUNC) &_snipsnop_test_performance_iterator_2, 1},
    {"_snipsnop_test_performance_iterator_disk", (DL_FUNC) &_snipsnop_test_performance_iterator_disk, 1},
    {"_snipsnop_test_performance_iterator_1d", (DL_FUNC) &_snipsnop_test_performance_iterator_1d, 1},
    {"_snipsnop_test_performance_iterator_2d", (DL_FUNC) &_snipsnop_test_performance_iterator_2d, 1},
    {"_snipsnop_test_snp_stats", (DL_FUNC) &_snipsnop_test_snp_stats, 1},
    {"_snipsnop_test_snp_stats_d", (DL_FUNC) &_snipsnop_test_snp_stats_d, 1},
    {"_snipsnop_test_sums", (DL_FUNC) &_snipsnop_test_sums, 1},
    {"_snipsnop_test_mu_sigma", (DL_FUNC) &_snipsnop_test_mu_sigma, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_snipsnop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
