# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SNPMatrixToIntegerMatrix <- function(pM) {
    .Call(`_snipsnop_SNPMatrixToIntegerMatrix`, pM)
}

getIndStats <- function(pM) {
    .Call(`_snipsnop_getIndStats`, pM)
}

readBedFileMemory <- function(filename, n_ind, n_snp) {
    .Call(`_snipsnop_readBedFileMemory`, filename, n_ind, n_snp)
}

test_ds <- function(DF, In) {
    .Call(`_snipsnop_test_ds`, DF, In)
}

test_ds2 <- function() {
    .Call(`_snipsnop_test_ds2`)
}

test_ds3 <- function(famFile) {
    .Call(`_snipsnop_test_ds3`, famFile)
}

test_readBedFileMemory <- function(filename, n_ind, n_snp, verbose = TRUE) {
    .Call(`_snipsnop_test_readBedFileMemory`, filename, n_ind, n_snp, verbose)
}

test_readBedFileDisk <- function(filename, n_ind, n_snp) {
    .Call(`_snipsnop_test_readBedFileDisk`, filename, n_ind, n_snp)
}

test_delete <- function(filename, n_ind, n_snp) {
    .Call(`_snipsnop_test_delete`, filename, n_ind, n_snp)
}

test_readModes <- function(filename, n_ind, n_snp) {
    .Call(`_snipsnop_test_readModes`, filename, n_ind, n_snp)
}

test_performance_iterator_default <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_default`, n)
}

test_performance_iterator_1 <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_1`, n)
}

test_performance_iterator_2 <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_2`, n)
}

test_performance_iterator_disk <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_disk`, n)
}

test_performance_iterator_1d <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_1d`, n)
}

test_performance_iterator_2d <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_2d`, n)
}

test_snp_stats <- function(n) {
    .Call(`_snipsnop_test_snp_stats`, n)
}

test_snp_stats_all <- function(n_ind, n_snp) {
    .Call(`_snipsnop_test_snp_stats_all`, n_ind, n_snp)
}

test_snp_stats_d <- function(n) {
    .Call(`_snipsnop_test_snp_stats_d`, n)
}

test_sums <- function(n) {
    .Call(`_snipsnop_test_sums`, n)
}

test_mu_sigma <- function(n) {
    .Call(`_snipsnop_test_mu_sigma`, n)
}

test_modes_setsigma_one <- function(mode) {
    .Call(`_snipsnop_test_modes_setsigma_one`, mode)
}

test_LD <- function(SNPnb1, SNPnb2) {
    .Call(`_snipsnop_test_LD`, SNPnb1, SNPnb2)
}

test_contingency <- function(SNPnb1, SNPnb2) {
    .Call(`_snipsnop_test_contingency`, SNPnb1, SNPnb2)
}

test_performance_stats_matrix <- function() {
    .Call(`_snipsnop_test_performance_stats_matrix`)
}

test_all_stats_matrix <- function() {
    .Call(`_snipsnop_test_all_stats_matrix`)
}

test_extract_Matrix <- function(keep) {
    .Call(`_snipsnop_test_extract_Matrix`, keep)
}

test_extract_Matrix_disk <- function(keep) {
    .Call(`_snipsnop_test_extract_Matrix_disk`, keep)
}

test_copyConstructor <- function() {
    invisible(.Call(`_snipsnop_test_copyConstructor`))
}

test_first_scnd_ind <- function() {
    .Call(`_snipsnop_test_first_scnd_ind`)
}

set_num_thread <- function(num) {
    invisible(.Call(`_snipsnop_set_num_thread`, num))
}

testsuite <- function(verbose = TRUE) {
    invisible(.Call(`_snipsnop_testsuite`, verbose))
}

