# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_readBedFileMemory <- function(filename, n_ind, n_snp) {
    .Call(`_snipsnop_test_readBedFileMemory`, filename, n_ind, n_snp)
}

test_readBedFileDisk <- function(filename, n_ind, n_snp) {
    .Call(`_snipsnop_test_readBedFileDisk`, filename, n_ind, n_snp)
}

test_delete <- function(filename, n_ind, n_snp) {
    .Call(`_snipsnop_test_delete`, filename, n_ind, n_snp)
}

test_readModes <- function(filename, n_ind, n_snp) {
    .Call(`_snipsnop_test_readModes`, filename, n_ind, n_snp)
}

test_performance_iterator_default <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_default`, n)
}

test_performance_iterator_1 <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_1`, n)
}

test_performance_iterator_2 <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_2`, n)
}

test_performance_iterator_disk <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_disk`, n)
}

test_performance_iterator_1d <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_1d`, n)
}

test_performance_iterator_2d <- function(n) {
    .Call(`_snipsnop_test_performance_iterator_2d`, n)
}

test_snp_stats <- function(n) {
    .Call(`_snipsnop_test_snp_stats`, n)
}

test_snp_stats_d <- function(n) {
    .Call(`_snipsnop_test_snp_stats_d`, n)
}

test_sums <- function(n) {
    .Call(`_snipsnop_test_sums`, n)
}

test_mu_sigma <- function(n) {
    .Call(`_snipsnop_test_mu_sigma`, n)
}

